/* DO NOT EDIT THIS FILE - it is machine generated */
#if (CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID)
#include <jni.h>
#endif
/* Header for class com_zerogame_client_AppPlugin */

#ifndef _Included_com_zerogame_pluginlibs_AppPlugin
#define _Included_com_zerogame_pluginlibs_AppPlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zerogame_client_AppPlugin
 * Method:    callMsgHandler
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zerogame_pluginlibs_AppPlugin_callMsgHandler
	(JNIEnv *, jobject, jint,jint);

JNIEXPORT void JNICALL Java_com_zerogame_pluginlibs_AppPlugin_callMsgHandler2
    (JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_com_zerogame_pluginlibs_AppPlugin_onNotifySelectImage
	(JNIEnv *env, jobject obj, jstring filePath);

#ifdef __cplusplus
}
#endif
#endif
