/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_zerogame_client_AppSDKManager */

#ifndef _Included_com_zerogame_sdkeasylibs_SDKObjectBase
#define _Included_com_zerogame_sdkeasylibs_SDKObjectBase
#ifdef __cplusplus
extern "C" {
#endif

/*======================= common function  ========================*/
JNIEXPORT void JNICALL Java_com_zerogame_sdkeasylibs_SDKObjectBase_loginResult
  (JNIEnv *, jobject, jboolean);
    
JNIEXPORT void JNICALL Java_com_zerogame_sdkeasylibs_SDKObjectBase_logoutResult
(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_zerogame_sdkeasylibs_SDKObjectBase_payResult
  (JNIEnv *, jobject, jboolean, jstring);

JNIEXPORT void JNICALL Java_com_zerogame_sdkeasylibs_SDKObjectBase_thirdLoginResult
    (JNIEnv *, jobject, jint, jstring);
    
JNIEXPORT void JNICALL Java_com_zerogame_sdkeasylibs_SDKObjectBase_initSdk
  (JNIEnv *, jobject,jint);

JNIEXPORT void JNICALL Java_com_zerogame_sdkeasylibs_SDKObjectBase_shareResult
  (JNIEnv *, jobject, jboolean);
    
JNIEXPORT void JNICALL Java_com_zerogame_sdkeasylibs_SDKObjectBase_videoCallBack
    (JNIEnv *, jobject,jint);
    
/*========================= platform function  ========================*/
JNIEXPORT void JNICALL Java_com_zerogame_sdkeasylibs_SDKObjectBase_setDeviceToken
    (JNIEnv *, jobject,jstring);
    
JNIEXPORT jstring JNICALL Java_com_snowcat_casino_AppSDKManager_getGooglePublicKey
    (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_zerogame_sdkeasylibs_SDKObjectBase_getSDKPrivateKey
    (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_zerogame_sdkeasylibs_SDKObjectBase_getSDKPublicKey
    (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
